fix: Dubble click in git settings button cause crash
Sketchware Pro v7.0.0-SNAPSHOT-d274d2a (150)
base.apk size: 128 MB (128239325 B)
Locale: en_GB
SDK version: 33
Brand: samsung
Manufacturer: samsung
Model: SM-M325F

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at android.view.LayoutInflater.from(LayoutInflater.java:294)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:213)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:207)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:193)
	at com.besome.sketch.export.GitConfigDialogFragment.onUserAndReposFetched(GitConfigDialogFragment.java:244)
	at com.besome.sketch.export.GitConfigDialogFragment.lambda$authorize$7(GitConfigDialogFragment.java:180)
	at com.besome.sketch.export.GitConfigDialogFragment.$r8$lambda$n1Yhei0wqtzLtbbp0rWtCq24xW4(Unknown Source:0)
	at com.besome.sketch.export.GitConfigDialogFragment$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```